"""Sharing

Revision ID: 3730d968f3d0
Revises: 4c73345a2d1b
Create Date: 2022-01-31 17:15:13.994905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3730d968f3d0'
down_revision = '4c73345a2d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sharing', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_column('sharing')

    # ### end Alembic commands ###
