"""cohort column

Revision ID: 742d48d1acb8
Revises: af2af2277d4c
Create Date: 2021-07-13 17:07:19.618951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742d48d1acb8'
down_revision = 'af2af2277d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('cohort', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'cohort')
    # ### end Alembic commands ###
