"""Precomments

Revision ID: a0d873d038a9
Revises: 3696aed15bb4
Create Date: 2022-02-27 21:38:35.363243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d873d038a9'
down_revision = '3696aed15bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subrating',
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.Column('precomment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['precomment_id'], ['precomment.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], )
    )
    op.create_table('subrating_history',
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('precomment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['precomment_id'], ['precomment.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subrating_history')
    op.drop_table('subrating')
    op.drop_table('precomment')
    # ### end Alembic commands ###
