"""init

Revision ID: a18b7593de7c
Revises: 
Create Date: 2021-03-31 13:14:13.200045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18b7593de7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_name'), 'dataset', ['name'], unique=True)
    op.create_table('rater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rater_email'), 'rater', ['email'], unique=True)
    op.create_index(op.f('ix_rater_username'), 'rater', ['username'], unique=True)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('extension', sa.String(length=8), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=16), nullable=True),
    sa.Column('session', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_image_name'), 'image', ['name'], unique=True)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('rater_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['rater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_timestamp'), 'ratings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_timestamp'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_image_name'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_rater_username'), table_name='rater')
    op.drop_index(op.f('ix_rater_email'), table_name='rater')
    op.drop_table('rater')
    op.drop_index(op.f('ix_dataset_name'), table_name='dataset')
    op.drop_table('dataset')
    # ### end Alembic commands ###
