"""Add cohort to image

Revision ID: d25e829b8d16
Revises: eea6ea3c80eb
Create Date: 2021-07-12 10:43:40.372000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25e829b8d16'
down_revision = 'eea6ea3c80eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('cohort', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'cohort')
    # ### end Alembic commands ###
