"""task alerts format

Revision ID: eea6ea3c80eb
Revises: 9b1b0a7008fe
Create Date: 2021-07-11 13:53:27.062092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea6ea3c80eb'
down_revision = '9b1b0a7008fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('icon', sa.String(length=18), nullable=True))
    op.add_column('task', sa.Column('alert_color', sa.String(length=18), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'alert_color')
    op.drop_column('task', 'icon')
    # ### end Alembic commands ###
